POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZXNpdG91MTYiLCJpZCI6IjY3OTFjMmQ5YzUzOTFjMjk0ZjdlMDYzYSIsImlhdCI6MTczNzY2OTgzNiwiZXhwIjoxNzM3NjczNDM2fQ.jdoopTcZ4aMYrZmvfdui1yi9Jip_8kBXm1wicHFaOyw
// alesitou16

{
  "title": "Successful blog",
  "author": "Alejandro Diaz Crivelli",
  "url": "https://github.com/diazale16",
  "likes": 16112001
}

###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2NzkxYzI5Y2M1MzkxYzI5NGY3ZTA2MzYiLCJpYXQiOjE3Mzc2NTI0NzYsImV4cCI6MTczNzY1NjA3Nn0.qDvqKcjb6wAaQrmPY-u_3p2qkJjBtGBuFMfyXkFRch4
// admin

{
  "title": "Authorized blog",
  "author": "Welix Wiaz Wrivelli",
  "url": "https://weeeeelix.com"
}

###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2NzkxYzI5Y2M1MzkxYzI5NGY3ZTA2MzYiLCJpYXQiOjE3Mzc2NTI0NzYsImV4cCI6MTczNzY1NjA3Nn0.qDvqKcjb6wAaQrmPY-u_3p2qkJjBtGBuFMfyXkFRch4
// admin

{
  "title": "Middlware supremacy",
  "author": "FSO Tutor",
  "url": "https://asdasdasd.com"
}
